# Generated by Django 3.0.7 on 2020-06-26 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ('-created_at',)},
        ),
    ]
